calibre_config:
    folders:
        - "/home/loreto/filu/ln-eBooks/lnLibraries/allInOne"
        - "/home/loreto/filu/ln-eBooks/lnLibraries/new_Entries"
        - "/home/loreto/filu/ln-eBooks/lnLibraries/Ale"

    current_library: null
    extensions:
        - epub


# epubs:
#     folders:
#         - '/home/loreto/filu/ln-eBooks/Calderone'
#         - '/home/loreto/filu/ln-eBooks/new_books'

    current_library: null
    extensions:
        - epub


# calderone/
#      epubs/
#         author_name/
#      text/
#         author_name/
main_epubs_path:  '/home/loreto/filu/ln-eBooks/ln_extracted'
authors_list:  'authors.yaml'

files_to_skip: []
    # - "Waylon University.02. La scommessa - Ilsa Madden-Mills"
    # - "Non ho paura del buio - Dugoni, Robert"
    # - "Faster_ Il brivido dell'amore - Paola Chiozza"
    # - "Figlio della Luna - Delrai, Malia"
    # - "Una semplice coincidenza - Irene Pistolato"
    # - "Amor en llamas - Kristen Callihan"
    # - "Faster - Paola Chiozza"

# authors:
    # !include authors.yaml#authors
