# ---

#########################################################
main:
    logger:
        filename: /tmp/eBooks.log
        enable: true
        level: info
        console: false
        disp_date: true
        disp_fullpath_module: true
        disp_time: true
        modules: []
        rotation_filesize: 10485760
        rotation_nfiles: 5

    # dbase_name: Ln_eBooks_TEST

#########################################################
# -             eBook directories
#########################################################
ebooks:

    dbase_name: Ln_eBooks

    epub_input_dir:
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/To_Be_Evalueated
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/New_books
        # /mnt/k/Download/Telegram/ePubs

        # - /mnt/k/Download/ePub/err
    epub_target_dir:
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/New_books
        # /mnt/k/Download/ePub_work
