# ---

#########################################################
Main:


#########################################################
# -             eBook directories
#########################################################
directories:
    epub:
        - /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre Portable/Ln_Library/LoretoBooks/Connelly, Michael/Debito di sangue (9)
        # - /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre Portable/Ln_Library/LoretoBooks
        # - /mnt/k/Filu/LnDisk/GIT-REPO/LnEbook/eBooks_for_test