# ---

#########################################################
main:
    # dbase_name: Ln_eBooks_TEST
    dbase_name: Ln_eBooks

#########################################################
# -             eBook directories
#########################################################
    epub_input_dir:
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/To_Be_Evalueated
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/New_books
        # /mnt/k/Download/Telegram/ePubs

        # - /mnt/k/Download/ePub/err
    epub_target_dir:
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/New_books
        # /mnt/k/Download/ePub_work
