# ---

#########################################################
Main:


#########################################################
# -             eBook directories
#########################################################
directories:
    epub_input_dir:
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/Ln_to_be_processed
        # /mnt/k/Filu/LnDisk/GIT-REPO/eBooks/eBooks_for_test

        # - /mnt/k/Download/ePub/err
    epub_target_dir:
      /mnt/k/Download/ePub_work