# ---

#########################################################
Main:


#########################################################
# -             eBook directories
#########################################################
directories:
    epub_input_dir:
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/To_Be_Evalueated
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/LoretoBooks/D., Mirta
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/ToBeRead/Locke, Attica
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/LoretoBooks
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/ToBeRead/Connelly, Michael
        # /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/Ln_Library/Ln_to_be_processed
        # /mnt/k/Filu/LnDisk/GIT-REPO/eBooks/eBooks_for_test

        # - /mnt/k/Download/ePub/err
    epub_target_dir:
        /mnt/k/Filu/LnDisk/Ln-eBooks/Calibre_Portable/New_books
        # /mnt/k/Download/ePub_work
